### ISSUE TITLE
Bugs report

### ISSUE THREAD

**Issue by stephencheng** [yurikhan/kitty-grab#3]
Firstly, this is great plugin for kitty, thanks for the work, it is what I am looking for.

There are quite a few things don't work quite right at moment.

I can only manage to fine tune and customise keys, like j/k/h/l for cursor movement,  y to yank, the other mappings I have tried hard, but none worked or behaved in weird way. And it is better to mimic the key bindings by default in vim style

Here are a few things I think it requires more work:

a. page up/down, ctrl+f/b
b. v for visual selection mode, if it is possible
c. the column selection just does not work. In fact, I enable alt key in my mac, and none of the mapping using alt key works. Not sure why.
d. not sure how to do search, or if this is possible.

Thank you

**Comment by yurikhan** [comment]
> other mappings I have tried hard, but none worked or behaved in weird way.

I might do something about it if you actually describe what you tried, what you expected, and what you got.

> And it is better to mimic the key bindings by default in vim style

No, it isn’t. E.g. on a Colemak keyboard, h/j/k/l makes no sense at all.

> page up/down, ctrl+f/b

Page up/down is a good idea. What do you mean by Ctrl+F/B? Moving forward/backward by one character already works, it’s `move right` and `move left`.

> v for visual selection mode, if it is possible

It’s possible, I just had no need for it, because all selections were possible using Shift+ and Alt+arrows so far. It might become necessary if/when I add search.

> the column selection just does not work. In fact, I enable alt key in my mac, and none of the mapping using alt key works. Not sure why.

Do Alt+arrows work at all for you in Kitty? E.g. if you bind something in the Kitty config, does that work?

Also, if you bind column selection to other keys in grab.conf, does it work then?

> not sure how to do search, or if this is possible.

Search is currently not implemented, but it’s a good idea.

**Comment by yurikhan** [comment]
Also, next time, please open a separate issue for each bug or feature request.

I am closing this now; feel free to subscribe to notifications on #4 and #5, and/or continue discussion here.
