### ISSUE TITLE
Question: how do you make the Ansi color displayed flawlessly? and can I do it in vim?

### ISSUE THREAD

**Issue by stephencheng** [yurikhan/kitty-grab#6]
My goal for me to make his copy mode work is always to try to use vim key-binding as my top priority. So I did bunch of tries:

1. Load a customised vimrc and config kitty to use it as pager
2. Use AnsiEsc plugin to try to keep the color 

However it works partially but not entirely, which will depends on what programs actually does the coloring in the first place. Some lines have been restored perfectly, some lines are either not or partially restored.

So my question is, can I borrow your implementation of "intact" of the original buffer and apply the same to my approach above? Not sure if you have tried using vim, you might have, if so, would you please just teach me the lesson so that I won't bump to the wall again.

Thanks

**Comment by yurikhan** [comment]
I did try using Vim as a grabber, with a short custom vimrc. But I was dissatisfied by the fact that I lost all color when grabbing.

I had a glance at AnsiEsc and Improved AnsiEsc. When I saw that one advertised feature of _Improved_ AnsiEsc is support for _16_ colors — in this year 2019, in a 24-bit terminal — I said “FFFFFUUUUUUUUUUUUUU” and started working on my own grabber implementation.

I didn’t do anything specifically to get the original buffer. Kitty just lets me take the window text, with color sequences and line markers. Because kitty-grab’s UI is specifically tailored to run in Kitty, redisplaying it is just a matter of replaying the same sequences to the terminal. Any general-purpose program such as Vim, that is designed to run in every terminal, is going to have to understand the escape sequences for any color modes Kitty supports before it can do anything useful with them.

You might be able to hack on (Improved) AnsiEsc to teach them to handle 256-color and 24-bit sequences, or convince other people to do it. That will be useful not just for you but for others who want to use Vim as a pager.

**Comment by stephencheng** [comment]
Thanks for sharing.

I think the AnsiEsc or whatever other vim plugin won't be able to handle this flawlessly, simply because different terminal app use different ways to render the colors, it's impossible(hard) to implement against so many possibilities.

I will wait a little bit for your plugin to be maturer.
